# Generated by Django 6.0.2 on 2026-02-09 17:26

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100, verbose_name='Анонимный покупатель')),
                ('original_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('abc_category', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], db_index=True, max_length=1, null=True, verbose_name='Категория')),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True, verbose_name='Последний раз был')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Тариф на эл. энергию',
                'verbose_name_plural': 'Тарифы на эл. энергию',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100, verbose_name='Покупатель')),
                ('mobile', models.CharField(blank=True, max_length=12, unique=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Эл. почта')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ['client'],
                'indexes': [models.Index(fields=['mobile'], name='homebrew_bu_mobile_82a5a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Тип напитка',
                'verbose_name_plural': 'Типы напитков',
                'indexes': [models.Index(fields=['title'], name='homebrew_ca_title_df8cba_idx')],
            },
        ),
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('strength', models.CharField(choices=[('35', '35'), ('38.5', '38.5'), ('40', '40'), ('42', '42'), ('70', '70'), ('96.6', '96.6')], default='40', max_length=100, verbose_name='Крепость')),
                ('quantity', models.PositiveSmallIntegerField(default=0, help_text='Указывать как 0.5л x кол-во', verbose_name='Доступное кол-во')),
                ('description', models.TextField(blank=True, default='Описание будет добавлено позже', null=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('image', models.ImageField(blank=True, upload_to='brew/%Y/%m/%d')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='homebrew.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Напиток',
                'verbose_name_plural': 'Напитки',
                'ordering': ['title', 'category'],
            },
        ),
        migrations.CreateModel(
            name='CategoryCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Оборудование', 'Оборудование'), ('Ингредиенты', 'Ингредиенты'), ('Прочее', 'Прочее')], max_length=20, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Вид расхода',
                'verbose_name_plural': 'Виды расходов',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='homebrew_ca_title_744b2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата покупки/оплаты')),
                ('title', models.CharField(max_length=70, verbose_name='Наименование')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
                ('weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Масса')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена за ед./кг.')),
                ('shop', models.CharField(choices=[('Mgn', 'Магнит'), ('5', 'Пятёрочка'), ('Nah', 'Находка'), ('Nov', 'Новатор'), ('Pbd', 'Победа'), ('Svet', 'Светофор'), ('Mon', 'Монетка'), ('Sam', 'Самоварщик'), ('Ozon', 'ОЗОН'), ('WB', 'Wildberries'), ('Ali', 'AliExpress'), ('Par', 'Парус'), ('Oth', 'Прочие')], default='Sam', max_length=10, verbose_name='Магазин')),
                ('comment', models.TextField(blank=True, verbose_name='Заметки')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Заполняется автоматически (count*price или weight*price)', max_digits=10, null=True, verbose_name='Итого')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='homebrew.categorycost', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Расходы',
                'verbose_name_plural': 'Расходы',
                'ordering': ['date', 'title', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RECT', 'Ректификация'), ('DSTL', 'Дистилляция'), ('VCDS', 'Вакуумная дист-ция'), ('MCRT', 'Мацерация'), ('NDRF', 'НДРФ'), ('OTHR', 'Прочее')], default='DSTL', max_length=4)),
                ('time_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало')),
                ('time_finish', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('breakdown', models.BooleanField(default=False)),
                ('start', models.DecimalField(blank=True, decimal_places=1, max_digits=8, verbose_name='Начальные показания')),
                ('end', models.DecimalField(blank=True, decimal_places=1, max_digits=8, verbose_name='Конечные показания')),
                ('total', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('end'), '-', models.F('start')), output_field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Израсходовано кВт*ч'))),
                ('total_time', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('time_finish'), '-', models.F('time_start')), output_field=models.DurationField())),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, null=True)),
                ('comment', models.TextField(blank=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Расход электроэнергии',
                'verbose_name_plural': 'Расходы электроэнергии',
                'ordering': ['time_start'],
                'constraints': [models.CheckConstraint(condition=models.Q(('time_finish__gt', models.F('time_start'))), name='finish_after_start')],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('brew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homebrew.brew')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homebrew.category')),
            ],
            options={
                'verbose_name': 'Вариант продукта',
                'verbose_name_plural': 'Варианты продукта',
                'ordering': ['brew__title', 'category__title'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date0', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата продажи')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('discount', models.SmallIntegerField(default=0, verbose_name='Скидка')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментарий')),
                ('total_price', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('price'), '*', models.F('count')), output_field=models.PositiveIntegerField())),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='homebrew.category', verbose_name='Категория')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homebrew.buyer', verbose_name='Покупатель')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homebrew.productvariant', verbose_name='Вариант товара')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['date', 'variant', 'discount'],
            },
        ),
        migrations.CreateModel(
            name='DemoIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата продажи')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('total_price', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('price'), '*', models.F('count')), output_field=models.PositiveIntegerField())),
                ('original_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('order_group_id', models.IntegerField(blank=True, null=True, verbose_name='ID группы заказа')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='homebrew.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homebrew.demobuyer')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homebrew.productvariant')),
            ],
            options={
                'verbose_name': 'Демо Продажа',
                'verbose_name_plural': 'Демо Продажи',
            },
        ),
        migrations.CreateModel(
            name='VariantPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homebrew.productvariant')),
            ],
            options={
                'verbose_name': 'Динамика цены',
                'verbose_name_plural': 'Динамика цен',
                'ordering': ['variant', 'start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='brew',
            index=models.Index(fields=['title'], name='homebrew_br_title_1df213_idx'),
        ),
        migrations.AddConstraint(
            model_name='brew',
            constraint=models.UniqueConstraint(fields=('title', 'slug', 'category'), name='unique_brew'),
        ),
        migrations.AddIndex(
            model_name='cost',
            index=models.Index(fields=['date'], name='homebrew_co_date_595b5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('brew', 'category')},
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['client', 'date'], name='homebrew_in_client__691539_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['category', 'date'], name='homebrew_in_categor_56b0db_idx'),
        ),
    ]
