# Generated by Django 6.0.2 on 2026-02-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Заполняется автоматически триггерными функциями Postgres (count*price или weight*price)', max_digits=10, null=True, verbose_name='Итого'),
        ),
    ]
