# Generated by Django 6.0.2 on 2026-02-14 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='homebrew.categorycost', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
    ]
